name: $(Date:yyyyMMdd.HHmm)

resources:
  containers:
  - container: build
    image: ubuntu:16.04
    options: '--name build -v /usr/bin/docker:/tmp/docker:ro'
  - container: ubuntu_16_04
    image: ubuntu:16.04

jobs:
- job: linux_dotnet
  displayName: 'Linux (dotnet)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: build
  steps:
    - script: /tmp/docker exec -t -u 0 build $(Build.SourcesDirectory)/build/dotnet/linux/install.sudo.sh
      displayName: Install sudo
    - template: build/dotnet/linux/build.yml

- template: build/dotnet/linux/verify.yml
  parameters:
    container: ubuntu_16_04
