name: $(Date:yyyyMMdd.HHmm)

resources:
  containers:
  - container: build
    image: ubuntu:16.04
    options: '--name build -v /usr/bin/docker:/tmp/docker:ro'
  - container: ubuntu_16_04
    image: ubuntu:16.04
  - container: ubuntu_17_10
    image: ubuntu:17.10
  - container: ubuntu_18_04
    image: ubuntu:18.04
  - container: ubuntu_latest
    image: ubuntu:latest
  - container: centos_7
    image: centos:7
  - container: dotnet_2_0
    image: microsoft/dotnet:2.0-runtime
  - container: dotnet_latest
    image: microsoft/dotnet:latest

jobs:
- job: linux_dotnet
  displayName: 'Linux (dotnet)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: build
  steps:
    - script: /tmp/docker exec -t -u 0 build $(Build.SourcesDirectory)/build/dotnet/linux/install.sudo.sh
      displayName: Install sudo
    - template: build/dotnet/linux/build.yml

- template: build/dotnet/linux/verify.yml
  parameters:
    container: ubuntu_16_04

- template: build/dotnet/linux/verify.yml
  parameters:
    container: ubuntu_17_10

- template: build/dotnet/linux/verify.yml
  parameters:
    container: ubuntu_18_04

- template: build/dotnet/linux/verify.yml
  parameters:
    container: ubuntu_latest

- template: build/dotnet/linux/verify.yml
  parameters:
    container: centos_7

- template: build/dotnet/linux/verify.yml
  parameters:
    container: dotnet_2_0

- template: build/dotnet/linux/verify.yml
  parameters:
    container: dotnet_latest
