name: $(Date:yyyyMMdd.HHmm)

resources:
  containers:
  - container: ubuntu
    image: ubuntu:bionic
    options: '--name ci-container -v /usr/bin/docker:/tmp/docker:ro'

jobs:
- job: linux
  displayName: 'Linux (dotnet)'
  pool:
    vmImage: 'Ubuntu 16.04'
  container: ubuntu
  steps:
    - template: build/container.yml
      parameters:
        type: 'dotnet'
        platform: 'linux'